<?php

namespace Modules\P4_ReportesMonitoreoAuditoria\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;
use Maatwebsite\Excel\Facades\Excel;
use Modules\P4_ReportesMonitoreoAuditoria\Services\ReporteCatalogoService;
use Modules\P4_ReportesMonitoreoAuditoria\Services\ReporteIAInterpretacionService;
use Modules\P4_ReportesMonitoreoAuditoria\Services\ReporteGeneradorService;
use Modules\P4_ReportesMonitoreoAuditoria\Services\AuditoriaService;
use Modules\P4_ReportesMonitoreoAuditoria\Requests\InterpretarReporteIARequest;
use Modules\P4_ReportesMonitoreoAuditoria\Requests\GenerarReporteIARequest;
use Modules\P4_ReportesMonitoreoAuditoria\Exports\ReporteGenericoExport;

class ReporteIAController extends Controller
{
    public function __construct(
        private readonly ReporteIAInterpretacionService $interpretacion,
        private readonly ReporteGeneradorService $generador
    ) {}

    /**
     * Returns the catalog of available report types.
     */
    public function tiposDisponibles(): JsonResponse
    {
        $catalogo = ReporteCatalogoService::catalogo();
        $lista = array_map(fn($tipo, $info) => [
            'tipo' => $tipo,
            'titulo' => $info['titulo'],
            'descripcion' => $info['descripcion'],
            'columnas' => $info['columnas'],
            'filtros_disponibles' => $info['filtros_disponibles'],
        ], array_keys($catalogo), $catalogo);

        return response()->json(['tipos' => array_values($lista)]);
    }

    /**
     * Interprets a natural language text and returns structured report intent.
     * No SQL is generated by the AI layer — only keyword matching.
     */
    public function interpretar(InterpretarReporteIARequest $request): JsonResponse
    {
        $resultado = $this->interpretacion->interpretar($request->texto);

        if (!$resultado['exitoso']) {
            return response()->json($resultado, 200);
        }

        AuditoriaService::registrar(
            $request->user()->id,
            'Interpretó solicitud de reporte por voz: ' . $request->texto,
            'ReportesIA',
            $request
        );

        return response()->json($resultado);
    }

    /**
     * Generates and downloads a report in PDF or Excel format.
     * Data is queried from the database using validated, whitelisted report types.
     */
    public function generar(GenerarReporteIARequest $request)
    {
        $tipo = $request->tipo_reporte;
        $formato = $request->formato;
        $filtros = $request->filtros ?? [];

        if (!ReporteCatalogoService::existe($tipo)) {
            return response()->json(['message' => 'Este tipo de reporte no está disponible.'], 403);
        }

        $datos = $this->generador->obtenerDatos($tipo, $filtros);

        if (empty($datos['filas'])) {
            return response()->json(['message' => 'No existen datos para los filtros seleccionados.'], 404);
        }

        AuditoriaService::registrar(
            $request->user()->id,
            "Generó reporte IA: {$tipo} en {$formato}",
            'ReportesIA',
            $request,
            json_encode($filtros)
        );

        $nombreArchivo = $this->nombreArchivo($tipo, $formato);

        if ($formato === 'excel') {
            return Excel::download(
                new ReporteGenericoExport($datos['filas'], $datos['columnas'], $datos['titulo']),
                $nombreArchivo
            );
        }

        // PDF via DomPDF
        $filtrosAplicados = array_filter($filtros);
        $pdf = Pdf::loadView('p4-reportes.generico', [
            'titulo' => $datos['titulo'],
            'columnas' => $datos['columnas'],
            'filas' => $datos['filas'],
            'descripcion' => ReporteCatalogoService::get($tipo)['descripcion'] ?? '',
            'generado_en' => $datos['generado_en'],
            'filtrosAplicados' => $filtrosAplicados,
        ])->setPaper('a4', 'landscape');

        return $pdf->download($nombreArchivo);
    }

    /**
     * Returns a JSON preview of the first 10 rows for display before export.
     */
    public function vistaPrevia(Request $request): JsonResponse
    {
        $request->validate([
            'tipo_reporte' => ['required', 'string'],
            'filtros' => ['nullable', 'array'],
        ]);

        $tipo = $request->tipo_reporte;

        if (!ReporteCatalogoService::existe($tipo)) {
            return response()->json(['message' => 'Este tipo de reporte no está disponible.'], 403);
        }

        $datos = $this->generador->obtenerDatos($tipo, $request->filtros ?? []);

        return response()->json([
            'titulo' => $datos['titulo'],
            'columnas' => $datos['columnas'],
            'filas' => array_slice($datos['filas'], 0, 10),
            'total' => $datos['total'],
            'mostrando' => min(10, $datos['total']),
        ]);
    }

    private function nombreArchivo(string $tipo, string $formato): string
    {
        $fecha = now()->format('Ymd_His');
        $ext = $formato === 'excel' ? 'xlsx' : 'pdf';
        return "reporte_{$tipo}_{$fecha}.{$ext}";
    }
}
